version: '3.9'

services:

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${postgress_user}
      POSTGRES_PASSWORD: ${postgress_password}
      POSTGRES_DB: ${postgres_db_name}
    ports:
      - "${postgress_exteral_port}:${postgres_interal_port}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${redis_username}
      RABBITMQ_DEFAULT_PASS: ${redis_password}
    ports:
      - "${redis_exteral_port}:${redis_interal_port}"
      - "${redis_interface_exteral_port}:${redis_interface_interal_port}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    restart: always
    ports:
      - "${app_port}:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

volumes:
  pg_data:
  grafana-storage: