version: '3.9'

services:

  loki:
    image: grafana/loki:2.9.0
    container_name: loki
    ports:
      - "${LOKI_PORT}:${LOKI_PORT}"
    command: -config.file=/etc/loki/local-config.yaml
    user: root
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data:/tmp/loki
    env_file:
      - .env
    environment:
      - TZ=${TZ}
    restart: unless-stopped


  promtail:
    image: grafana/promtail:2.9.0
    container_name: promtail
    volumes:
      - ./logs:/var/log/app
      - ./promtail-config.yaml:/etc/promtail/promtail.yaml
    command: -config.file=/etc/promtail/promtail.yaml
    restart: unless-stopped


  grafana:
    image: grafana/grafana:10.2.2
    container_name: grafana
    ports:
      - "${GRAFANA_PORT}:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: ${postgress_user}
      POSTGRES_PASSWORD: ${postgress_password}
      POSTGRES_DB: ${postgres_db_name}
    ports:
      - "${postgress_exteral_port}:${postgres_interal_port}"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${redis_username}
      RABBITMQ_DEFAULT_PASS: ${redis_password}
    ports:
      - "${redis_exteral_port}:${redis_interal_port}"
      - "${redis_interface_exteral_port}:${redis_interface_interal_port}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - .env

volumes:
  pg_data:
  grafana-storage: